version: '3.4'

services:
  heisln.car.api:
    image: ${DOCKER_REGISTRY-}heislncarapi
    build:
      context: .
      dockerfile: Heisln.Car.Api/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
  db:
    image: mysql:8.0.23
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: qwertzuio
        MYSQL_USER: test
        MYSQL_PASSWORD: pass@word1234
        MYSQL_DATABASE: NapDb
    restart: always
  adminer:
    image: adminer
    depends_on:
        - db
    environment:
        ADMINER_DEFAULT_DB_DRIVER: mysql
        ADMINER_DEFAULT_DB_HOST: db
        ADMINER_DEFAULT_DB_NAME: NapDb
        ADMINER_DESIGN: flat
        ADMINER_PLUGINS: tables-filter tinymce
    ports:
        - 8001:8080

