version: '3.4'

services:
  heisln-api-dev:
    container_name: heisln-api-dev
    image: ${DOCKER_REGISTRY-}heislncarapi
    build:
      context: .
      dockerfile: Heisln.Car.Api/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - heisln-db-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
  heisln-db-dev:
    container_name: heisln-db-dev
    image: mysql:8.0.23
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: qwertzuio
        MYSQL_USER: test
        MYSQL_PASSWORD: pass@word1234
        MYSQL_DATABASE: NapDb
    restart: always

